server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/opal
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jackson:
    date-format: YYYY-MM-DD
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: status

logging:
  level:
    org:
      springframework:
        web: DEBUG